/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.AppLogs;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AppLogs extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"avro.AppLogs\",\"namespace\":\"avro.avro.AppLogs\",\"fields\":[{\"name\":\"logItem\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"LogItemType\",\"fields\":[{\"name\":\"headers\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"HeadersType\",\"fields\":[{\"name\":\"userId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"timestamp\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"appName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"appVersion\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"platformName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"platformVersion\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"userLat\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"userLong\",\"type\":[\"null\",\"double\"],\"default\":null}]}],\"default\":null},{\"name\":\"actions\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ActionsType\",\"fields\":[{\"name\":\"action\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"value\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null},{\"name\":\"context\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ContextType\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"value\",\"type\":[\"null\",\"string\"],\"default\":null}]},\"default\":[]}],\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public avro.AppLogs.LogItemType logItem;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AppLogs() {}

  /**
   * All-args constructor.
   */
  public AppLogs(avro.AppLogs.LogItemType logItem) {
    this.logItem = logItem;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return logItem;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: logItem = (avro.AppLogs.LogItemType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'logItem' field.
   */
  public avro.AppLogs.LogItemType getLogItem() {
    return logItem;
  }

  /**
   * Sets the value of the 'logItem' field.
   * @param value the value to set.
   */
  public void setLogItem(avro.AppLogs.LogItemType value) {
    this.logItem = value;
  }

  /** Creates a new avro.AppLogs RecordBuilder */
  public static avro.AppLogs.AppLogs.Builder newBuilder() {
    return new avro.AppLogs.AppLogs.Builder();
  }
  
  /** Creates a new avro.AppLogs RecordBuilder by copying an existing Builder */
  public static avro.AppLogs.AppLogs.Builder newBuilder(avro.AppLogs.AppLogs.Builder other) {
    return new avro.AppLogs.AppLogs.Builder(other);
  }
  
  /** Creates a new avro.AppLogs RecordBuilder by copying an existing avro.AppLogs instance */
  public static avro.AppLogs.AppLogs.Builder newBuilder(avro.AppLogs.AppLogs other) {
    return new avro.AppLogs.AppLogs.Builder(other);
  }
  
  /**
   * RecordBuilder for avro.AppLogs instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AppLogs>
    implements org.apache.avro.data.RecordBuilder<AppLogs> {

    private avro.AppLogs.LogItemType logItem;

    /** Creates a new Builder */
    private Builder() {
      super(avro.AppLogs.AppLogs.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.AppLogs.AppLogs.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.logItem)) {
        this.logItem = data().deepCopy(fields()[0].schema(), other.logItem);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing avro.AppLogs instance */
    private Builder(avro.AppLogs.AppLogs other) {
            super(avro.AppLogs.AppLogs.SCHEMA$);
      if (isValidValue(fields()[0], other.logItem)) {
        this.logItem = data().deepCopy(fields()[0].schema(), other.logItem);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'logItem' field */
    public avro.AppLogs.LogItemType getLogItem() {
      return logItem;
    }
    
    /** Sets the value of the 'logItem' field */
    public avro.AppLogs.AppLogs.Builder setLogItem(avro.AppLogs.LogItemType value) {
      validate(fields()[0], value);
      this.logItem = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'logItem' field has been set */
    public boolean hasLogItem() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'logItem' field */
    public avro.AppLogs.AppLogs.Builder clearLogItem() {
      logItem = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AppLogs build() {
      try {
        AppLogs record = new AppLogs();
        record.logItem = fieldSetFlags()[0] ? this.logItem : (avro.AppLogs.LogItemType) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
